name: Compile and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1.0.1
        with:
          version: nightly

      - name: Run mainnet tests
        run: forge test --mc Mainnet --fork-url https://rpc.ankr.com/eth

      - name: Run arbitrum tests
        run: forge test --mc Arbitrum --fork-url https://arb1.arbitrum.io/rpc